<?php
/**
 * Created by PhpStorm.
 * User: PC
 * Date: 2016/3/29
 * Time: 20:20
 */
namespace app\modules\user\controllers;

use yii\base\Exception;
use yii\helpers\Json;
use yii\helpers\Url;
use yii\web\Controller;
//use common\models\table\User;

use backend\models\UserAccess;


/**
 * Access controller for the `user` module
 */
class AccessController extends Controller
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $foo=\Yii::$app->user;
        $foo->on($foo::EVENT_AFTER_LOGIN,[$this,'afterLogin']);
        $foo->on($foo::EVENT_AFTER_LOGOUT,[$this,'afterLogout']);
    }

    /*
     * 登录
     * */
    public function actionLogin()
    {
        if(\Yii::$app->request->isPost){
            $RQ=\Yii::$app->request;
            $user_info=UserAccess::findOne(['email'=>$RQ->post("email")]);
            if($user_info){
                if(\Yii::$app->getSecurity()->validatePassword($RQ->post("password"),$user_info->password)){
                    $identity=UserAccess::findIdentity($user_info->id);
                    if($user_info->is_active){
                        if($user_info->pid<1){
                            $cookie_time=3600*24*7;
                        }else{
                            $cookie_time=3600*5;
                        }
                        if(\Yii::$app->user->login($identity,$cookie_time)){
                            \Yii::info('登录成功'.$user_info->id.'-ip'.\Yii::$app->request->userIP,__METHOD__);
                            //用户登录,cookie7天有效,子帐号则为5个小时
                            return $this->redirect(['/index/index']);
                        }else{
                            \Yii::$app->session->setFlash("AlertMsg","登录失败！");
                        }
                    }else{
                        \Yii::$app->session->setFlash('AlertMsg','账号未激活');
                    }
                }else{
                    \Yii::$app->session->setFlash("AlertMsg","邮箱或密码错误！");
                }
            }else{
                \Yii::$app->session->setFlash("AlertMsg","用户名不存在！");
            }
            \Yii::$app->session->setFlash("re_email",$RQ->post("email"));
        }

        return $this->renderPartial("login");
    }

    /*
     * 注册
     * */
    public function actionRegister()
    {
        $RQ=\Yii::$app->request;
        if($RQ->isPost){
            $model=new \common\models\table\User();
            if($RQ->post('password')!=$RQ->post('confirmpassword')){
                \Yii::$app->session->setFlash("AlertMsg","两次输入密码不一致");
            }elseif(strlen($RQ->post('password'))<6){
                \Yii::$app->session->setFlash("AlertMsg","密码至少6个字符");
            }elseif($model::findOne(['email'=>$RQ->post("email")])){
                \Yii::$app->session->setFlash("AlertMsg","邮箱已注册！");
            }elseif($model::findOne(['name'=>$RQ->post("username")])){
                \Yii::$app->session->setFlash("AlertMsg","用户名已注册！");
            }else{
                $model->name=$RQ->post("username");
                $model->email=$RQ->post("email");
                $model->last_login_time=(string)time();
                $model->last_login_ip=$RQ->userIP;
                $model->login_times=0;
                $model->role="USER";
                $model->password = \Yii::$app->getSecurity()->generatePasswordHash($RQ->post("password"));
                $model->auth_key=\Yii::$app->security->generateRandomString();
                $model->access_token=\Yii::$app->security->generateRandomString();
                $model->expire=(string)(time()+3600*24*0.00001);
                $model->is_active=0;
                if($model->validate() && $model->save()){
                    \Yii::info('注册成功一人'.$model->id,__METHOD__);
                    $web=new \common\models\table\Web();
                    $web->admin=$model->id;
                    $newmodel=UserAccess::findOne($model->id);
                    if($web->save()){
                        $newmodel->wid=$web->id;
                    }else{
                        $newmodel->wid=0000;
                    }
                    if($newmodel->update()){
                        $active_link=Url::toRoute(['access/active','email'=>$model->email,'token'=>md5($model->access_token)],true);
                        $sendcontent='感谢您注册zx开发的网站，请点击链接确认您的认证邮箱。（如果邮箱内无法点击链接，请直接复制链接到浏览器打开）<br/><a href="'.$active_link.'">'.$active_link.'</a>';
                        $mail= \Yii::$app->mailer->compose();
                        $mail->setTo($model->email);
                        $mail->setSubject("注册邮箱认证");
                        $mail->setHtmlBody($sendcontent);
                        $mail->send();
                        \Yii::info('发送邮件到'.$model->email,__METHOD__);
                        \Yii::$app->session->setFlash("AlertMsg","我们已发送认证邮件到您的邮箱，请及时查看");
                        return $this->redirect(['access/login']);
                    }
                }else{
                    \Yii::$app->session->setFlash("AlertMsg",'注册失败'.$model->errors['email'][0]);
                    //print_r($model->errors['email'][0]);die;
                }
            }
            \Yii::$app->session->setFlash("re_username",$RQ->post("username"));
            \Yii::$app->session->setFlash("re_email",$RQ->post("email"));
        }
        return $this->renderPartial('register');
    }

    /*
     * 账号邮箱激活
     * */
    public function actionActive()
    {

        $info=UserAccess::find()->where(['email'=>\Yii::$app->request->get('email')])->one();


        if($info){
            if($info->is_active){
                return $this->redirect(['access/login','email'=>$info->email]);
            }else{
                if(\Yii::$app->request->get('token')==md5($info->access_token)){
                    $info->is_active=1;
                    if($info->save()){
                        \Yii::$app->session->setFlash('AlertMsg','账号激活成功');
                        return $this->redirect(['access/login','email'=>$info->email]);
                    }else{
                        print_r($info->getErrors());
                    }
                }
            }
        }else{
            \Yii::$app->session->setFlash('AlertMsg','邮箱不存在');
            return $this->redirect(['access/login']);
        }
    }

    /*
     * 退出登录
     * */
    public function actionLogout()
    {

        if(\Yii::$app->user->logout()){
            if(\Yii::$app->request->post('changepwd')){
                \Yii::$app->session->setFlash('AlertMsg','密码修改成功,你需要重新登录！');
            }
            return $this->redirect(['access/login']);
        }else{
            return $this->render(['/index/index']);
        }
    }


    /*
     * ajax 判断用户名是否被使用
     * */
    public function actionUsername()
    {


        $return['success']=true;

        try{
            if(!\Yii::$app->request->isAjax){
                throw new Exception("非法请求！");
            }

            if(\common\models\table\User::findOne(['name'=>\Yii::$app->request->get('name')])){

                throw new Exception("用户名已存在！");

            }

        }catch (Exception $e){

            $return['success']=false;

            $return['msg']=$e->getMessage();

        }

        Json::ajaxreturn($return);

    }





    protected function afterLogin()
    {
        $model=UserAccess::findOne(['id'=>\Yii::$app->user->getId()]);
        $model->login_times=$model->login_times+1;
        $model->last_login_time=(string)time();
        $model->last_login_ip=\Yii::$app->request->userIP;
        if ( $model->save() == false )
        {
            print_r($model->errors);die;
        }
    }

    protected function afterLogout(){
        $cookies=\Yii::$app->response->cookies;
        $cookies->remove('/admin/_backendIdentity');
    }
}